import "./globals.css";


export const metadata = {
  title: "Service Apartment Delhi | Rent Best Serviced Apartments Delhi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="min-h-screen">{children}</main>
      </body>
    </html>
  );
}
